### ISSUE TITLE
Plugin is not working accordingly

### ISSUE THREAD

**Issue by juliovedovatto** [unlight/tailwind-float-label#1]
Hello @unlight 

Thank you for this nice plugin. It will save some time while developing forms with Tailwind CSS, for sure!

But it seems it is not working anymore 🤔

Plase check: https://unlight.github.io/tailwind-float-label

![image](https://user-images.githubusercontent.com/320507/162210534-f5affc3f-5985-4cf7-81b9-4c635b4f43fa.png)

When you focus the field, nothing happens.

**Comment by unlight** [comment]
@juliovedovatto when it was working for you (which version)?
I've checked latest v1, v2 and it behavior is the same.

Label rises up when placeholder dissapers - when you start typing, not when field get focus.

https://user-images.githubusercontent.com/301732/162283116-c09363b4-3bfd-4f64-b33d-c894ec116a35.mp4

**Comment by juliovedovatto** [comment]
@unlight The example page is little confusing, I think I misinterpreted it 😅

Does your plugin have animations when a user interacts with the field? I was expecting some form of animation for when user 
focus the field or starts typing.

BTW, I'm using Tailwind 3

**Comment by unlight** [comment]
No worries.
There is no animation in this plugin, but you can add your custom style to label.
```ts tailwind.config.js
const postcss = require('postcss');

module.exports = {
	// ...
    plugins: [
        require('tailwind-float-label')({
            label: {
			   // Plugin defaults
                ['@apply leading-none text-xs px-1']: '',
                top: 0,
                left: '0.25rem',
			    // Animation
                // transition: 'all 250ms', // option 1
                ['@apply transition-transform']: '', // option 2
            },
        }),
    ],
};
```

Also, you can check [similar project and resources](https://github.com/unlight/tailwind-float-label#similar-projects) sections, there are some examples with animation.
